### PR TITLE
Docker agent

### PR DESCRIPTION
**Pull request by dbluhm**
A couple of updates to your docker work for the python reference agent.

### CODE REVIEW

**Comment by xaviernopre** [comment]
@dbluhm Thank you for your PR :-) . But I have questions about "network=host". It's a pitty to have double commands (double target in Makefile). Is it essential in your case to specify "network=host" ? I have tried on Debian 9.6, and Docker 18.09.0, and it works fine without this option... I just want to be sure to not add a double target if it is not really necessary... ;-)

**Comment by dbluhm** [comment]
As I noted in my additions to the README, the `network="host"` is unfortunately necessary in the case you want to interact with something on the host machine like, for example, the test suite, on a docker host running in Linux. Mac and Windows have the "docker.host.internal" route but this is not currently supported on Linux. This is a common enough use case that I think it would be helpful to have a shortcut to it. If you have a better way to provide this shortcut without adding a double target, I'm open to suggestions for sure :slightly_smiling_face:

**Comment by xaviernopre** [comment]
@dbluhm Hi :-) . I understand, but as I said, I have done a test on Debian, and the option `network="host"` is not needed. You are talking about "test suite", but unless I'm mistaken, there are no test suite in this project. Just to be sure, is this option necessary for you to run the demo ? This option enable the container to be in the same network than the host, but with port mapping (`-p $$PORT:$$PORT`), it seems to be enough to connect the browser in the host to the container, no ?

**Comment by dbluhm** [comment]
https://github.com/hyperledger/indy-agent/tree/master/test-suite

You should join us on the indy agent working group calls :smiley:

**Comment by dbluhm** [comment]
But I'll take your point and try to find a better alternative. Thanks!

**Comment by xaviernopre** [comment]
For Indy Agent working group calls, yes, it could be interesting, but it's complicated for me (different reasons...)... :-/ ... I'm happy with your PR, and impatient that my own PR could be merged ;-) . I just want to be sure to keep something as simple as possible. I'm on MacOs. My colleague is on Debian, so after your PR, we have tried my original solution, ans it works. So my questions to you ;-) . I just have take a look at `test-suite` but it is in another directory than `python` demo, so I suppose it's like another project, no really linked to Python demo. I just want to be sure if it's working like that in your computer ? And for information, `network="host"` is not compatible with port mapping `-p`, so if the first is enabled, the second must be removed (it's like an alternative). I hope we can find the "good" universal solution, so that my PR can be merged ;-)

**Pull request closed without merging**
